### ISSUE TITLE
SyntaxError when importing ccm

### ISSUE THREAD

**Issue by dizzydis** [codeix/pyaxl#1]
Not 100% sure if this is a code issue or not.
EDIT: Seems to be a Python 3 syntax. I wasn't aware this was specific to Python 3. So take this issue with a grain of salt. Thanks :)

Installed pyaxl v. 1.0.1 with pip:

```
C:\Python27\lib\site-packages\pip\_vendor\requests\packages\urllib3\util\ssl_.py
:79: InsecurePlatformWarning: A true SSLContext object is not available. This pr
events urllib3 from configuring SSL appropriately and may cause certain SSL conn
ections to fail. For more information, see https://urllib3.readthedocs.org/en/la
test/security.html#insecureplatformwarning.
  InsecurePlatformWarning
You are using pip version 6.1.1, however version 7.1.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Collecting pyaxl
C:\Python27\lib\site-packages\pip\_vendor\requests\packages\urllib3\util\ssl_.py
:79: InsecurePlatformWarning: A true SSLContext object is not available. This pr
events urllib3 from configuring SSL appropriately and may cause certain SSL conn
ections to fail. For more information, see https://urllib3.readthedocs.org/en/la
test/security.html#insecureplatformwarning.
  InsecurePlatformWarning
  Downloading pyaxl-1.0.1.tar.gz
Requirement already satisfied (use --upgrade to upgrade): setuptools in c:\pytho
n27\lib\site-packages\setuptools-15.2-py2.7.egg (from pyaxl)
Collecting suds-jurko (from pyaxl)
  Downloading suds-jurko-0.6.tar.bz2 (143kB)
    100% |################################| 147kB 196kB/s
Installing collected packages: suds-jurko, pyaxl
  Running setup.py install for suds-jurko
  Running setup.py install for pyaxl
Successfully installed pyaxl-1.0.1 suds-jurko-0.6
```

Seemed to install successfully.

Went to the python command line in cmd prompt (Win 7 currently) running python 2.7.5.

Ran the following and got the error shown:

```
Python 2.7.5 (default, May 15 2013, 22:43:36) [MSC v.1500 32 bit (Intel)] on win
32
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyaxl
>>> from pyaxl import ccm
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python27\lib\site-packages\pyaxl\ccm\__init__.py", line 1, in <module
>
    from pyaxl.ccm.common import *
  File "C:\Python27\lib\site-packages\pyaxl\ccm\common.py", line 3, in <module>
    from pyaxl.axlsql import AXLSQLUtils
  File "C:\Python27\lib\site-packages\pyaxl\axlsql.py", line 3, in <module>
    from pyaxl.axlhandler import AXLClient
  File "C:\Python27\lib\site-packages\pyaxl\axlhandler.py", line 84
    file=sys.stderr)
        ^
SyntaxError: invalid syntax
>>>
```

As mentioned in my edit it seems the print("Text",file=<file>) syntax is Python 3. Is that the intent? (I checked the page and didn't see that this module was specific to python 3).

Either way is this something that could this be easily changed?
Thanks!

**Comment by codeix** [comment]
This library was from the outset written for python 3. I will change this in the documentation, thanks for the hint. I think it's easier to install python3 in your setup instead of making this library python 2 compatible.

**Comment by dizzydis** [comment]
Awesome.  Glad to help out.  Thanks
