### ISSUE TITLE
Import definitions error

### ISSUE THREAD

**Issue by voiceguy123** [codeix/pyaxl#2]
I was trying to import definitions from the CUCM 11 AXL toolkit and I received the following error. Have you seen this type of error before?

PS C:\Users\nm\AppData\Local\Programs\Python\Python35\Scripts> .\pyaxl_import_wsdl "C:\RDM Logs\11.0\AXLAPI.wsdl"
"suds.reader.Reader.mangle" patched
Traceback (most recent call last):
  File "c:\users\nm\appdata\local\programs\python\python35\lib\urllib\request.py", line 1396, in open_local_file
    stats = os.stat(localfile)
FileNotFoundError: [WinError 3] The system cannot find the path specified: ''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\nm\AppData\Local\Programs\Python\Python35\Scripts\pyaxl_import_wsdl-script.py", line 9, in <module>
    load_entry_point('pyaxl==1.0.1', 'console_scripts', 'pyaxl_import_wsdl')()
  File "c:\users\nm\appdata\local\programs\python\python35\lib\site-packages\pyaxl\axlhandler.py", line 158, in import_wsdl
    client = Client(FILE_PREFIX % source, cache=cache, doctor=doctor)
  File "c:\users\nm\appdata\local\programs\python\python35\lib\site-packages\suds\client.py", line 115, in **init**
    self.wsdl = reader.open(url)
  File "c:\users\nm\appdata\local\programs\python\python35\lib\site-packages\suds\reader.py", line 150, in open
    d = self.fn(url, self.options)
  File "c:\users\nm\appdata\local\programs\python\python35\lib\site-packages\suds\wsdl.py", line 136, in **init**
    d = reader.open(url)
  File "c:\users\nm\appdata\local\programs\python\python35\lib\site-packages\suds\reader.py", line 74, in open
    d = self.download(url)
  File "c:\users\nm\appdata\local\programs\python\python35\lib\site-packages\suds\reader.py", line 92, in download
    fp = self.options.transport.open(Request(url))
  File "c:\users\nm\appdata\local\programs\python\python35\lib\site-packages\suds\transport\https.py", line 62, in open
    return HttpTransport.open(self, request)
  File "c:\users\nm\appdata\local\programs\python\python35\lib\site-packages\suds\transport\http.py", line 67, in open
    return self.u2open(u2request)
  File "c:\users\nm\appdata\local\programs\python\python35\lib\site-packages\suds\transport\http.py", line 132, in u2open
    return url.open(u2request, timeout=tm)
  File "c:\users\nm\appdata\local\programs\python\python35\lib\urllib\request.py", line 465, in open
    response = self._open(req, data)
  File "c:\users\nm\appdata\local\programs\python\python35\lib\urllib\request.py", line 483, in _open
    '_open', req)
  File "c:\users\nm\appdata\local\programs\python\python35\lib\urllib\request.py", line 443, in _call_chain
    result = func(*args)
  File "c:\users\nm\appdata\local\programs\python\python35\lib\urllib\request.py", line 1374, in file_open
    return self.open_local_file(req)
  File "c:\users\nm\appdata\local\programs\python\python35\lib\urllib\request.py", line 1414, in open_local_file
    raise URLError(exp)
urllib.error.URLError: <urlopen error [WinError 3] The system cannot find the path specified: ''>

**Comment by yuehan81** [comment]
Hi Voiceguy123,

I did not see that 8 days ago you also posted already the same problem. Today I ran into the same error on Windows but a few days ago it worked on Linux. I looked a little more on this github project and saw there were 2 branches. There is a branch for windows support where the axlhandler.py has been patched for windows. So if you change the axlhandler.py that probably came by using pip to install pyaxl with the following version https://github.com/codeix/pyaxl/blob/2572f09c8f20d7366bde906613d1ee84f2d007ed/src/pyaxl/axlhandler.py you should be able to do the pyaxl_import_wsdl without errors. ;-)

**Comment by codeix** [comment]
Hi there,

First of all, glad to see that people are using pyaxl.
Unfortunately I didn't work for the company anymore where I have created this libary. This means that I have no possibility to test pyaxl with the callmanger.

If you can confirm that the branch "windows_support" works without errors, then I'll merge it into the master branch.

**Comment by voiceguy123** [comment]
I was just able to get back to this today, apologies for the delay. It did work rather well. I swapped the contents of the file and ran the executable again to attempt importing and they imported right away. Thanks for the suggestion!
