### ISSUE TITLE
Problem importing AXL schema with python 3.5 and Windows 7

### ISSUE THREAD

**Issue by yuehan81** [codeix/pyaxl#3]
Hi,

First off thank you very much for this great implementation/simplification for talking AXL with the Cisco callmanager from python. It looks very promising.

I tried using your modules and succeeded on doing some simple things on Python for Linux but I cannot get the pyaxl_import_wsdl.exe import the AXL scheme on Windows 7 with python 3.5.
It seems to pass your    "if not os.path.exists(args.source)" test in the import_wsdl() function but then it goes wrong. Below the error I get. Could you help me finding the solution to this problem?
I am very new to Python and programming in general so excuse me if this is problem simple to solve.  :-)

I also tried with a non existing path name and then I got the "AXL doesn't exist" as that is what you print if the path does not exist.

PS C:\Users\Test\Python\axlsqltoolkit\schema\9.1> pyaxl_import_wsdl -p "C:/Users/Test/Python/axlsqltoolkit/schema/9.1/AXLAPI.wsdl"
"suds.reader.Reader.mangle" patched
AXL doesn't exist
PS C:\Users\Proximus\Python\axlsqltoolkit\schema\9.1> pyaxl_import_wsdl -p "C:/Users/Proximus/Python/axlsqltoolkit/schem
a/9.1/AXLAPI.wsdl"
"suds.reader.Reader.mangle" patched
Traceback (most recent call last):
  File "c:\python\python35\lib\urllib\request.py", line 1411, in open_local_file
    stats = os.stat(localfile)
FileNotFoundError: [WinError 3] The system cannot find the path specified: ''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\python\python35\lib\runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\python\python35\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python\Python35\Scripts\pyaxl_import_wsdl.exe__main__.py", line 9, in <module>
  File "c:\python\python35\lib\site-packages\pyaxl\axlhandler.py", line 158, in import_wsdl
    client = Client(FILE_PREFIX % source, cache=cache, doctor=doctor)
  File "c:\python\python35\lib\site-packages\suds\client.py", line 115, in **init**
    self.wsdl = reader.open(url)
  File "c:\python\python35\lib\site-packages\suds\reader.py", line 150, in open
    d = self.fn(url, self.options)
  File "c:\python\python35\lib\site-packages\suds\wsdl.py", line 136, in **init**
    d = reader.open(url)
  File "c:\python\python35\lib\site-packages\suds\reader.py", line 74, in open
    d = self.download(url)
  File "c:\python\python35\lib\site-packages\suds\reader.py", line 92, in download
    fp = self.options.transport.open(Request(url))
  File "c:\python\python35\lib\site-packages\suds\transport\https.py", line 62, in open
    return HttpTransport.open(self, request)
  File "c:\python\python35\lib\site-packages\suds\transport\http.py", line 67, in open
    return self.u2open(u2request)
  File "c:\python\python35\lib\site-packages\suds\transport\http.py", line 132, in u2open
    return url.open(u2request, timeout=tm)
  File "c:\python\python35\lib\urllib\request.py", line 466, in open
    response = self._open(req, data)
  File "c:\python\python35\lib\urllib\request.py", line 484, in _open
    '_open', req)
  File "c:\python\python35\lib\urllib\request.py", line 444, in _call_chain
    result = func(*args)
  File "c:\python\python35\lib\urllib\request.py", line 1389, in file_open
    return self.open_local_file(req)
  File "c:\python\python35\lib\urllib\request.py", line 1429, in open_local_file
    raise URLError(exp)
urllib.error.URLError: <urlopen error [WinError 3] The system cannot find the path specified: ''>

Kind Regards,

Johan Sermon

**Comment by codeix** [comment]
see my post #2

**Comment by codeix** [comment]
the new release v1.1 is on pypi

**Comment by yuehan81** [comment]
Thank you very much for adapting your code ;-)

**Comment by codeix** [comment]
You're welcome. If you have other bugfixes, improvements or API extensions, please send me a pull request.  I'll merge it for you and deliver a new version on pypi. So other people can profit from it.
